const ActionTypes = {
  POSTS_REQUESTED: 'POSTS_REQUESTED',
  POSTS_RECEIVED: 'POSTS_RECEIVED',
  POSTS_REJECTED: 'POSTS_REJECTED',

  SEND_POST_REQUESTED: 'SEND_POST_REQUESTED',
  SEND_POST_RECEIVED: 'SEND_POST_RECEIVED',
  SEND_POST_REJECTED: 'SEND_POST_REJECTED',

  USER_REQUESTED: 'USER_REQUESTED',
  USER_RECEIVED: 'USER_RECEIVED',
  USER_REJECTED: 'USER_REJECTED',

  EDIT_USER_REQUESTED: 'EDIT_USER_REQUESTED',
  EDIT_USER_RECEIVED: 'EDIT_USER_RECEIVED',
  EDIT_USER_REJECTED: 'EDIT_USER_REJECTED',

};

export default ActionTypes;
