const ActionTypes = {
  POSTS_REQUESTED: 'POSTS_REQUESTED',
  USER_REQUESTED: 'USER_REQUESTED',
  EDIT_USER_REQUESTED: 'EDIT_USER_REQUESTED',
  SEND_POST_REQUESTED: 'SEND_POST_REQUESTED',
};

export default ActionTypes;
