const ActionTypes = {
  POSTS_REQUESTED: 'POSTS_REQUESTED',
  POSTS_RECEIVED: 'POSTS_RECEIVED',
  POSTS_REJECTED: 'POSTS_REJECTED',

  SEND_POST_REQUESTED: 'SEND_POST_REQUESTED',
  SEND_POST_RECEIVED: 'SEND_POST_RECEIVED',
  SEND_POST_REJECTED: 'SEND_POST_REJECTED',

  USER_REQUESTED: 'USER_REQUESTED',
  USER_RECEIVED: 'USER_RECEIVED',
  USER_REJECTED: 'USER_REJECTED',

  EDIT_USER_REQUESTED: 'EDIT_USER_REQUESTED',
  EDIT_USER_RECEIVED: 'EDIT_USER_RECEIVED',
  EDIT_USER_REJECTED: 'EDIT_USER_REJECTED',

  SIGN_IN_REQUESTED: 'SIGN_IN_REQUESTED',
  SIGN_IN_RECEIVED: 'SIGN_IN_RECEIVED',
  SIGN_IN_REJECTED: 'SIGN_IN_REJECTED',

  SIGN_UP_REQUESTED: 'SIGN_UP_REQUESTED',
  SIGN_UP_RECEIVED: 'SIGN_UP_RECEIVED',
  SIGN_UP_REJECTED: 'SIGN_UP_REJECTED',

  SIGN_OUT_REQUESTED: 'SIGN_OUT_REQUESTED',
  SIGN_OUT_RECEIVED: 'SIGN_OUT_RECEIVED',
  SIGN_OUT_REJECTED: 'SIGN_OUT_REJECTED',

  AUTH_REQUESTED: 'AUTH_REQUESTED',
  AUTH_RECEIVED: 'AUTH_RECEIVED',
  AUTH_REJECTED: 'AUTH_REJECTED',

  GOOGLE_AUTH_REQUESTED: 'GOOGLE_AUTH_REQUESTED',
  GOOGLE_AUTH_RECEIVED: 'GOOGLE_AUTH_RECEIVED',
  GOOGLE_AUTH_REJECTED: 'GOOGLE_AUTH_REJECTED',
};

export default ActionTypes;
